INSERT INTO roles (code, name, description, is_deleted)
VALUES ('CUSTOMER', 'Customer', 'Người mua sắm trên hệ thống', false),
       ('SELLER', 'Seller', 'Chủ shop bán hàng', false),
       ('ADMIN', 'Administrator', 'Quản trị toàn hệ thống', false),
       ('STAFF_SUPPORT', 'Support Staff', 'Nhân viên chăm sóc khách hàng', false),
       ('INVENTORY_MANAGER', 'Inventory Manager', 'Quản lý kho', false),
       ('DELIVERY_MANAGER', 'Delivery Manager', 'Quản lý vận chuyển', false),
       ('PAYMENT_MANAGER', 'Payment Manager', 'Quản lý thanh toán', false);
INSERT INTO permissions (code, name, description, path, http_method, is_deleted)
VALUES ('PRODUCT_LIST', 'View product list', '', '/api/v1/products', 'GET', false),
       ('PRODUCT_VIEW', 'View product detail', '', '/api/v1/products/{id}', 'GET', false),
       ('PRODUCT_CREATE', 'Create product', '', '/api/v1/products', 'POST', false),
       ('PRODUCT_UPDATE', 'Update product', '', '/api/v1/products/{id}', 'PUT', false),
       ('PRODUCT_DELETE', 'Delete product', '', '/api/v1/products/{id}', 'DELETE', false),
       ('ORDER_LIST', 'View order list', '', '/api/v1/orders', 'GET', false),
       ('ORDER_VIEW', 'View order detail', '', '/api/v1/orders/{id}', 'GET', false),
       ('ORDER_CREATE', 'Create order', '', '/api/v1/orders', 'POST', false),
       ('ORDER_CANCEL', 'Cancel order', '', '/api/v1/orders/{id}/cancel', 'POST', false),
       ('ORDER_UPDATE_STATUS', 'Update order status', '', '/api/v1/orders/{id}/status', 'PATCH', false),
       ('CART_VIEW', 'View cart', '', '/api/v1/cart', 'GET', false),
       ('CART_ADD', 'Add item to cart', '', '/api/v1/cart/add', 'POST', false),
       ('CART_REMOVE', 'Remove item', '', '/api/v1/cart/remove/{id}', 'DELETE', false),
       ('CART_CLEAR', 'Clear cart', '', '/api/v1/cart/clear', 'DELETE', false),
       ('CUSTOMER_VIEW', 'View customer profile', '', '/api/v1/customers/{id}', 'GET', false),
       ('CUSTOMER_UPDATE', 'Update customer profile', '', '/api/v1/customers/{id}', 'PATCH', false),
       ('INVENTORY_VIEW', 'View inventory', '', '/api/v1/inventory', 'GET', false),
       ('INVENTORY_UPDATE', 'Update inventory', '', '/api/v1/inventory/{id}', 'PATCH', false),
       ('DELIVERY_CREATE', 'Create delivery', '', '/api/v1/delivery', 'POST', false),
       ('DELIVERY_UPDATE', 'Update delivery', '', '/api/v1/delivery/{id}', 'PATCH', false),
       ('DELIVERY_TRACK', 'Track delivery', '', '/api/v1/delivery/{tracking}', 'GET', false),
       ('PAYMENT_VIEW', 'View payments', '', '/api/v1/payments', 'GET', false),
       ('PAYMENT_REFUND', 'Refund payment', '', '/api/v1/payments/{id}/refund', 'POST', false),
       ('PAYMENT_VERIFY', 'Verify payment', '', '/api/v1/payments/{id}/verify', 'POST', false);